spring.application.name=WorkBridge

spring.datasource.url=jdbc:postgresql://localhost:5432/workbridge
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

jwt.secret=7be88f948fb0aa3e252d5ffa48c29bba97c97cee238923b182ab612026a37d0e